version: '2'
services: 
  postgres:
    container_name: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./productsupplierPG.csv:/productsupplier.csv
      - ./productPG.csv:/product.csv
      - ./supplierPG.csv:/supplier.csv
      - ./customerPG.csv:/customer.csv
      - ./orderPG.csv:/order.csv
      - ./orderitemPG.csv:/orderitem.csv
      - ./setup_postgres_model.sql:/docker-entrypoint-initdb.d/create_script.sql
      - ./olap_benchmark_postgres.jar:/olap_benchmark_postgres.jar
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgresdb
    build:
      context: .
      dockerfile: ./Dockerfile_postgres
  hbase-master:
    image: blueskyareahm/hbase-base:2.1.3
    command: master
    ports:
      - 16000:16000
      - 16010:16010
    volumes:
      - ./productsupplierHB.csv:/productsupplier.csv
      - ./productHB.csv:/product.csv
      - ./supplierHB.csv:/supplier.csv
      - ./customerHB.csv:/customer.csv
      - ./orderHB.csv:/order.csv
      - ./orderitemHB.csv:/orderitem.csv
      - ./hbase_setup_olap_model.jar:/hbase_setup_olap_model.jar
      - ./olap_benchmark_hbase.jar:/olap_benchmark_hbase.jar

  hbase-regionserver:
    image: blueskyareahm/hbase-base:2.1.3
    command: regionserver
    ports:
      - 16030:16030
      - 16201:16201
      - 16301:16301

  zookeeper:
    image: blueskyareahm/hbase-zookeeper:3.4.13
    ports:
      - 2181:2181