SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA postgresdb;


ALTER SCHEMA postgresdb OWNER TO pg_database_owner;


COMMENT ON SCHEMA postgresdb IS 'standard postgresdb schema';

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE postgresdb.PRODUCT (
	ID  INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
    BRAND VARCHAR(50) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    SIZE INTEGER NOT NULL,
    CONTAINER VARCHAR(50) NOT NULL,
    PRICE VARCHAR(50) NOT NULL,
    COMMENT VARCHAR(50)
);

CREATE TABLE postgresdb.SUPPLIER (
    ID  INTEGER PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(200) NOT NULL,
    PHONE VARCHAR(50) NOT NULL
);

CREATE TABLE postgresdb.PRODUCTSUPPLIER (
    ID INTEGER NOT NULL PRIMARY KEY,
    PRODUCT INTEGER NOT NULL,
    SUPPLIER INTEGER NOT NULL,
    AVAILABLE INTEGER NOT NULL,
    SUPPLY_COST REAL NOT NULL,
    COMMENT VARCHAR(200),
    CONSTRAINT fk_product
    FOREIGN KEY(PRODUCT) REFERENCES  postgresdb.PRODUCT(ID),
    CONSTRAINT fk_supplier
    FOREIGN KEY(SUPPLIER) REFERENCES  postgresdb.SUPPLIER(ID)
    
);

CREATE TABLE postgresdb.CUSTOMER(
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(200) NOT NULL,
    PHONE VARCHAR(50) NOT NULL,
    COMMENT VARCHAR(200)
);

CREATE TABLE postgresdb.ORDER(
    ID INTEGER PRIMARY KEY,
    CUSTOMER INTEGER NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    TOTAL_PRICE REAL NOT NULL,
    ENTRY_DATE DATE NOT NULL,
    PRIORITY VARCHAR(20) NOT NULL,
    COMMENT VARCHAR(200),
    CONSTRAINT fk_customer
    FOREIGN KEY(CUSTOMER) REFERENCES  postgresdb.CUSTOMER(ID)
);

CREATE TABLE postgresdb.ORDER_ITEM(
    ORDER_ID INTEGER NOT NULL,
    PRODUCT INTEGER NOT NULL,
    SUPPLIER INTEGER NOT NULL, 
    ORDER_NO INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL,
    BASE_PRICE REAL NOT NULL,
    DISCOUNT INTEGER NOT NULL,
    TAX REAL NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    SHIP_DATE DATE NOT NULL,
    COMMIT_DATE DATE NOT NULL,
    COMMENT VARCHAR(200),
    PRIMARY KEY(ORDER_ID,PRODUCT,SUPPLIER),
    CONSTRAINT fk_order
    FOREIGN KEY(ORDER_ID) REFERENCES  postgresdb.ORDER(ID),
    CONSTRAINT fk_product
    FOREIGN KEY(PRODUCT) REFERENCES  postgresdb.PRODUCT(ID),
    CONSTRAINT fk_supplier
    FOREIGN KEY(SUPPLIER) REFERENCES  postgresdb.SUPPLIER(ID)
);