version: '2'
services: 
  postgres:
      image: postgres:latest
      container_name: postgres
      ports:
        - "5433:5432"
      volumes:
        - ./setup_postgres_model.sql:/docker-entrypoint-initdb.d/create_script.sql
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgresdb
