
services: 
  hbase-master:
    image: blueskyareahm/hbase-base:2.1.3
    command: master
    ports:
      - 16000:16000
      - 16010:16010

  hbase-regionserver:
    image: blueskyareahm/hbase-base:2.1.3
    command: regionserver
    ports:
      - 16030:16030
      - 16201:16201
      - 16301:16301
  hbase-regionserver2:
    image: blueskyareahm/hbase-base:2.1.3
    command: regionserver
    ports:
      - 16130:16130
      - 16501:16501
      - 16601:16601

  zookeeper:
    image: blueskyareahm/hbase-zookeeper:3.4.13
    ports:
      - 2181:2181